name: Mark and close stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 60
        stale-issue-message: 'Marked as stale due to inactivity. Will be closed in 30 days.'
        stale-pr-message: 'Marked as stale due to inactivity. Will be closed in 30 days.'
        days-before-close: 30
        close-issue-message: 'Closed due to inactivity for 90 days.'
        close-pr-message: 'Closed due to inactivity for 90 days.'
        
